config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  root 'welcome#index'

  resources :contents

end

app/models/content.rb
class Content < ActiveRecord::Base
  validates :s3_bucket, presence: true

  def uploadfile=(file)
    self.filename = file.original_filename
    self.size = filse.size
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  def new
    @content = Content.new
  end

  def create
    @content = Content.new(content_params)
    upload_file = params[:content][:upload_filename]

    # get an instance of the S3 interface using the default configuration
    s3 = AWS::S3.new

    # get a bucket
    b = s3.buckets[@content.s3_bucket]

    # upload a file
    o = b.objects[upload_file.original_filename]
    o.write(upload_file.read, :acl => :public_read)

    @content.filename = upload_file.original_filename
    @content.size = upload_file.size
    @content.s3_url = o.public_url.to_s

    if @content.save
      redirect_to contents_path
    else
      render 'new'
    end
  end

  def index
    @contents = Content.all
  end

  def destroy
    @content = Content.find(params[:id])

    # get an instance of the S3 interface using the default configuration
    s3 = AWS::S3.new

    # get a bucket
    b = s3.buckets[@content.s3_bucket]

    # delete a file
    o = b.objects[@content.filename]
    o.delete()

    @content.destroy

    redirect_to contents_path
  end

  private
    def content_params
      params.require(:content).permit(:s3_bucket)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contents/index.html.erb
<h1>Contents#index</h1>

<%= link_to 'Upload a new file', new_content_path %>

<table>
  <tr>
    <th>File name</th>
    <th>Size</th>
    <th>S3 Bucket name</th>
    <th>&nbsp;</th>
  </tr>

  <% @contents.each do |content| %>
    <tr>
      <td><a href="<%= content.s3_url %>" target="_blank"><%= content.filename %></a></td>
      <td><%= content.size %></td>
      <td><%= content.s3_bucket %></td>
      <td><%= link_to 'Destroy', content_path(content),
                method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/contents/new.html.erb
<h1>Contents#new</h1>

<% if @content.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@content.errors.count, "error") %>
      prohibited this content from being saved:</h2>
    <ul>
      <% @content.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @content, :html => { multipart: true } do |f| %>
  <p>
    <%= f.label :s3_bucket %><br />
    <%= f.text_field :s3_bucket %>
  </p>
  <p>
    <%= f.label :upload_filename %><br />
    <%= f.file_field :upload_filename %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', contents_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Uploader</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>

<%= link_to 'My Contents', controller: 'contents' %>